### ISSUE TITLE
Doesn't work with Angular 7.2.11

### ISSUE THREAD

**Issue by Stajor** [sindresorhus/screenfull.js#130]
Angular: 7.2.11
Screenfull: 4.1.0

Directive
```
import {Directive, HostListener, Input} from '@angular/core';
import * as screenfull from 'screenfull';

@Directive({
  selector: '[fullscreen]'
})
export class FullscreenDirective {
    @Input() set fullscreen(el) {
        this.element = el;
    }
    @HostListener('click') onClick() {
        if (screenfull.enabled) {
            screenfull.request(this.element);
        }
    }

    private element;
}
```

Compilation Error:

```
ERROR in src/app/shared/directives/fullscreen.directive.ts(12,24): error TS2339: Property 'enabled' does not exist on type 'typeof import(".../node_modules/screenfull/dist/screenfull")'.
src/app/shared/directives/fullscreen.directive.ts(13,24): error TS2339: Property 'request' does not exist on type 'typeof import(".../node_modules/screenfull/dist/screenfull")'.

```

**Comment by KarKan88** [comment]
I'm also facing this issue. I think it is with **Screenfull: 4.1.0**, not angular version. My Angular version is 6.1.10

**Comment by tuckergordon** [comment]
Seems like this is a typing issue. If you need a quick (but admittedly ugly) fix before it's resolved, you can do `(screenfull as screenfull.Screenfull).enabled)`

**Comment by tuckergordon** [comment]
I think this is a duplicate of[ issue 126](https://github.com/sindresorhus/screenfull.js/issues/126)

**Comment by sindresorhus** [comment]
Duplicate of #126
